import type { JornadaStage, JornadaTask } from '@/app/types';

const RANK_LETTERS = [
  'Ferro',
  'Bronze',
  'Prata',
  'Ouro',
  'Platina',
  'Esmeralda',
  'Diamante',
  'Mythril',
  'Mestre',
  'Lendário',
] as const;

export const MOCK_STAGES: JornadaStage[] = [
  { id: 's1', order: 1, title: 'Ferro', rankLetter: 'Ferro', faixa: 'Preparação' },
  { id: 's2', order: 2, title: 'Bronze', rankLetter: 'Bronze', faixa: 'Preparação' },
  { id: 's3', order: 3, title: 'Prata', rankLetter: 'Prata', faixa: 'Preparação' },
  { id: 's4', order: 4, title: 'Ouro', rankLetter: 'Ouro', faixa: 'Consolidação' },
  { id: 's5', order: 5, title: 'Platina', rankLetter: 'Platina', faixa: 'Consolidação' },
  { id: 's6', order: 6, title: 'Esmeralda', rankLetter: 'Esmeralda', faixa: 'Consolidação' },
  { id: 's7', order: 7, title: 'Diamante', rankLetter: 'Diamante', faixa: 'Lapidação' },
  { id: 's8', order: 8, title: 'Mythril', rankLetter: 'Mythril', faixa: 'Lapidação' },
  { id: 's9', order: 9, title: 'Mestre', rankLetter: 'Mestre', faixa: 'Elite' },
  { id: 's10', order: 10, title: 'Lendário', rankLetter: 'Lendário', faixa: 'Elite' },
];

export { RANK_LETTERS };

export const MOCK_TASKS: JornadaTask[] = [
  // ---------- Etapa 1 – Ferro ----------
  { id: 'ferro-1', stageId: 's1', title: 'Boas-vindas + Visão Geral AI-Driven/AI First', status: 'pending', order: 1 },
  { id: 'ferro-2', stageId: 's1', title: 'Como usar os devquest agents do Devquest e modo Socrático', status: 'pending', order: 2 },
  { id: 'ferro-3', stageId: 's1', title: 'Conhecendo o VS Code para criação de código', status: 'pending', order: 3 },
  { id: 'ferro-4', stageId: 's1', title: 'GitHub Copilot Seu Assistente de Código Inteligente', status: 'pending', order: 4 },
  { id: 'ferro-5', stageId: 's1', title: 'Gemini CLI – Seu colega experiente no terminal', status: 'pending', order: 5 },
  { id: 'ferro-6', stageId: 's1', title: 'Comunidade Guilda DevQuest', status: 'pending', order: 6 },
  { id: 'ferro-7', stageId: 's1', title: 'Como usar a plataforma de aulas', status: 'pending', order: 7 },
  { id: 'ferro-8', stageId: 's1', title: 'Como usar o Discord', status: 'pending', order: 8 },
  { id: 'ferro-9', stageId: 's1', title: 'Solicitação de Certificado com Reconhecimento do MEC', status: 'pending', order: 9 },
  { id: 'ferro-10', stageId: 's1', title: 'O que é HTML e como funciona', status: 'pending', order: 10 },
  { id: 'ferro-11', stageId: 's1', title: 'Meta tags e favicon', status: 'pending', order: 11 },
  { id: 'ferro-12', stageId: 's1', title: 'Tags essenciais: headings, parágrafos, listas', status: 'pending', order: 12 },
  { id: 'ferro-13', stageId: 's1', title: 'Exercício - Tags essenciais: headings, parágrafos, listas', status: 'pending', order: 13 },
  { id: 'ferro-14', stageId: 's1', title: 'Atributos, links e imagens', status: 'pending', order: 14 },
  { id: 'ferro-15', stageId: 's1', title: 'Exercício - Atributos, links e imagens', status: 'pending', order: 15 },
  { id: 'ferro-16', stageId: 's1', title: 'Comentários', status: 'pending', order: 16 },
  { id: 'ferro-17', stageId: 's1', title: 'Exercício - Comentários em HTML', status: 'pending', order: 17 },
  { id: 'ferro-18', stageId: 's1', title: 'Tabelas em HTML', status: 'pending', order: 18 },
  { id: 'ferro-19', stageId: 's1', title: 'Exercício - Tabelas em HTML', status: 'pending', order: 19 },
  { id: 'ferro-20', stageId: 's1', title: 'Semântica no HTML - main, nav, section, header e footer', status: 'pending', order: 20 },
  { id: 'ferro-21', stageId: 's1', title: 'Exercício - Semântica no HTML - main, nav, section, header e footer', status: 'pending', order: 21 },
  { id: 'ferro-22', stageId: 's1', title: 'DevTools: inspecionando elementos e debug visual', status: 'pending', order: 22 },
  { id: 'ferro-23', stageId: 's1', title: 'IA no DevTools', status: 'pending', order: 23 },
  { id: 'ferro-24', stageId: 's1', title: 'O que é CSS e como conectar ao HTML', status: 'pending', order: 24 },
  { id: 'ferro-25', stageId: 's1', title: 'Display: block, inline, inline-block, none', status: 'pending', order: 25 },
  { id: 'ferro-26', stageId: 's1', title: 'Exercício - Display: block, inline, inline-block, none', status: 'pending', order: 26 },
  { id: 'ferro-27', stageId: 's1', title: 'Seletores, classes e IDs', status: 'pending', order: 27 },
  { id: 'ferro-28', stageId: 's1', title: 'Exercício - Seletores, classes e IDs', status: 'pending', order: 28 },
  { id: 'ferro-29', stageId: 's1', title: 'Cores, fontes e estilização de texto', status: 'pending', order: 29 },
  { id: 'ferro-30', stageId: 's1', title: 'Exercício - Cores, fontes e estilização de texto', status: 'pending', order: 30 },
  { id: 'ferro-31', stageId: 's1', title: 'Box model padding, margin e border', status: 'pending', order: 31 },
  { id: 'ferro-32', stageId: 's1', title: 'Exercício - Box Model: Padding, Margin, Border e Box-Sizing', status: 'pending', order: 32 },
  { id: 'ferro-33', stageId: 's1', title: 'Aprendi sobre o conceito: Estrutura semântica HTML', description: 'Conceito-chave', status: 'pending', order: 33 },
  { id: 'ferro-34', stageId: 's1', title: 'Aprendi sobre o conceito: Box Model', description: 'Conceito-chave', status: 'pending', order: 34 },
  { id: 'ferro-35', stageId: 's1', title: 'Aprendi sobre o conceito: DevTools', description: 'Conceito-chave', status: 'pending', order: 35 },
  { id: 'ferro-36', stageId: 's1', title: 'Aprendi sobre o conceito: Uso de IAs no desenvolvimento', description: 'Conceito-chave', status: 'pending', order: 36 },

  // ---------- Etapa 2 – Bronze ----------
  { id: 'bronze-1', stageId: 's2', title: 'Introdução Flexbox', status: 'pending', order: 1 },
  { id: 'bronze-2', stageId: 's2', title: 'Flex Direction', status: 'pending', order: 2 },
  { id: 'bronze-3', stageId: 's2', title: 'Justify Content', status: 'pending', order: 3 },
  { id: 'bronze-4', stageId: 's2', title: 'Exercícios Flexbox - Justify-content', status: 'pending', order: 4 },
  { id: 'bronze-5', stageId: 's2', title: 'Align Itens', status: 'pending', order: 5 },
  { id: 'bronze-6', stageId: 's2', title: 'Exercícios - Align-items', status: 'pending', order: 6 },
  { id: 'bronze-7', stageId: 's2', title: 'Flex Wrap e Flex Flow', status: 'pending', order: 7 },
  { id: 'bronze-8', stageId: 's2', title: 'Align Content', status: 'pending', order: 8 },
  { id: 'bronze-9', stageId: 's2', title: 'Gap', status: 'pending', order: 9 },
  { id: 'bronze-10', stageId: 's2', title: 'Grow', status: 'pending', order: 10 },
  { id: 'bronze-11', stageId: 's2', title: 'Basis', status: 'pending', order: 11 },
  { id: 'bronze-12', stageId: 's2', title: 'Shrink', status: 'pending', order: 12 },
  { id: 'bronze-13', stageId: 's2', title: 'Flex', status: 'pending', order: 13 },
  { id: 'bronze-14', stageId: 's2', title: 'Order', status: 'pending', order: 14 },
  { id: 'bronze-15', stageId: 's2', title: 'Align Self', status: 'pending', order: 15 },
  { id: 'bronze-16', stageId: 's2', title: 'Dicas finais', status: 'pending', order: 16 },
  { id: 'bronze-17', stageId: 's2', title: 'O que é? começando layout com grid', status: 'pending', order: 17 },
  { id: 'bronze-18', stageId: 's2', title: 'Propriedades grid: grid-template-columns, grid-template-rows, gap', status: 'pending', order: 18 },
  { id: 'bronze-19', stageId: 's2', title: 'Exercício - Grid template columns e grid template rows', status: 'pending', order: 19 },
  { id: 'bronze-20', stageId: 's2', title: 'Grid: ocupando espaços', status: 'pending', order: 20 },
  { id: 'bronze-21', stageId: 's2', title: 'grid  area', status: 'pending', order: 21 },
  { id: 'bronze-22', stageId: 's2', title: 'grid template area', status: 'pending', order: 22 },
  { id: 'bronze-23', stageId: 's2', title: 'Exercício - Grid área', status: 'pending', order: 23 },
  { id: 'bronze-24', stageId: 's2', title: 'grid auto-fill e auto-fit', status: 'pending', order: 24 },
  { id: 'bronze-25', stageId: 's2', title: 'Exercício - Grid auto-fill e auto-fit', status: 'pending', order: 25 },
  { id: 'bronze-26', stageId: 's2', title: 'O que é responsividade?', status: 'pending', order: 26 },
  { id: 'bronze-27', stageId: 's2', title: 'O que é media query?', status: 'pending', order: 27 },
  { id: 'bronze-28', stageId: 's2', title: 'Exercício Responsividade - Media querie', status: 'pending', order: 28 },
  { id: 'bronze-29', stageId: 's2', title: 'Introdução ao Terminal e comandos básicos', status: 'pending', order: 29 },
  { id: 'bronze-30', stageId: 's2', title: 'Introdução Git/GitHub', status: 'pending', order: 30 },
  { id: 'bronze-31', stageId: 's2', title: 'Configurando git', status: 'pending', order: 31 },
  { id: 'bronze-32', stageId: 's2', title: 'Estado dos arquivos na prática', status: 'pending', order: 32 },
  { id: 'bronze-33', stageId: 's2', title: 'Como gerar token de acesso pessoal no Github', status: 'pending', order: 33 },
  { id: 'bronze-34', stageId: 's2', title: 'Git no VS Code', status: 'pending', order: 34 },
  { id: 'bronze-35', stageId: 's2', title: 'GitHub Pages', status: 'pending', order: 35 },
  { id: 'bronze-36', stageId: 's2', title: 'Explicação do projeto e Planejameto do projeto com IA', status: 'pending', order: 36 },
  { id: 'bronze-37', stageId: 's2', title: 'Setup do projeto + GitHub', status: 'pending', order: 37 },
  { id: 'bronze-38', stageId: 's2', title: 'Estrutura base com HTML semântico', status: 'pending', order: 38 },
  { id: 'bronze-39', stageId: 's2', title: 'Estilização inicial com CSS global', status: 'pending', order: 39 },
  { id: 'bronze-40', stageId: 's2', title: 'Criando o HTML do menu', status: 'pending', order: 40 },
  { id: 'bronze-41', stageId: 's2', title: 'Estilizando o menu', status: 'pending', order: 41 },
  { id: 'bronze-42', stageId: 's2', title: 'Criando Banner/Hero', status: 'pending', order: 42 },
  { id: 'bronze-43', stageId: 's2', title: 'Layout com Flexbox nos cards', status: 'pending', order: 43 },
  { id: 'bronze-44', stageId: 's2', title: 'Galeria com Grid responsivo', status: 'pending', order: 44 },
  { id: 'bronze-45', stageId: 's2', title: 'Rodapé', status: 'pending', order: 45 },
  { id: 'bronze-46', stageId: 's2', title: 'Responsividade do menu', status: 'pending', order: 46 },
  { id: 'bronze-47', stageId: 's2', title: 'Responsividade das demais seções', status: 'pending', order: 47 },
  { id: 'bronze-48', stageId: 's2', title: 'Correção do Menu', status: 'pending', order: 48 },
  { id: 'bronze-49', stageId: 's2', title: 'Deploy no Pages', status: 'pending', order: 49 },
  { id: 'bronze-50', stageId: 's2', title: 'Projeto: Projeto E-commerce HTML e CSS', status: 'pending', order: 50 },
  { id: 'bronze-51', stageId: 's2', title: 'Prática Frontend Mentor — HTML & CSS', status: 'pending', order: 51 },
  { id: 'bronze-52', stageId: 's2', title: 'Aprendi sobre o conceito: Layout moderno com Flexbox e Grid', description: 'Conceito-chave', status: 'pending', order: 52 },
  { id: 'bronze-53', stageId: 's2', title: 'Aprendi sobre o conceito: Responsividade mobile-first', description: 'Conceito-chave', status: 'pending', order: 53 },
  { id: 'bronze-54', stageId: 's2', title: 'Aprendi sobre o conceito: Fluxo Git básico (add/commit/push)', description: 'Conceito-chave', status: 'pending', order: 54 },

  // ---------- Etapa 3 – Prata ----------
  { id: 'prata-1', stageId: 's3', title: 'Variáveis, console e template literal', status: 'pending', order: 1 },
  { id: 'prata-2', stageId: 's3', title: 'Exercício - Variáveis, console e template literal', status: 'pending', order: 2 },
  { id: 'prata-3', stageId: 's3', title: 'Tipos primitivos', status: 'pending', order: 3 },
  { id: 'prata-4', stageId: 's3', title: 'Exercício Tipos primitivos', status: 'pending', order: 4 },
  { id: 'prata-5', stageId: 's3', title: 'Operadores lógicos - Parte 1', status: 'pending', order: 5 },
  { id: 'prata-6', stageId: 's3', title: 'Operadores lógicos - Parte 2', status: 'pending', order: 6 },
  { id: 'prata-7', stageId: 's3', title: 'Exercício - Operadores lógicos', status: 'pending', order: 7 },
  { id: 'prata-8', stageId: 's3', title: 'Operadores matemáticos', status: 'pending', order: 8 },
  { id: 'prata-9', stageId: 's3', title: 'Exercício - Operadores matemáticos', status: 'pending', order: 9 },
  { id: 'prata-10', stageId: 's3', title: 'Condicionais (if else e switch)', status: 'pending', order: 10 },
  { id: 'prata-11', stageId: 's3', title: 'Exercício - Condicionais com if else e switch', status: 'pending', order: 11 },
  { id: 'prata-12', stageId: 's3', title: 'Loops (for, while e do while)', status: 'pending', order: 12 },
  { id: 'prata-13', stageId: 's3', title: 'Exercício - Laço de repetição com for, while e do while', status: 'pending', order: 13 },
  { id: 'prata-14', stageId: 's3', title: 'Funções - Um dos conceitos mais importantes do JavaScript', status: 'pending', order: 14 },
  { id: 'prata-15', stageId: 's3', title: 'Exercícios - Funções no JavaScript', status: 'pending', order: 15 },
  { id: 'prata-16', stageId: 's3', title: 'Funções anônimas e arrow functions', status: 'pending', order: 16 },
  { id: 'prata-17', stageId: 's3', title: 'Exercício - Função com Arrow function', status: 'pending', order: 17 },
  { id: 'prata-18', stageId: 's3', title: 'Arrays', status: 'pending', order: 18 },
  { id: 'prata-19', stageId: 's3', title: 'Objetos', status: 'pending', order: 19 },
  { id: 'prata-20', stageId: 's3', title: 'Exercício - Percorrendo arrays com forEach', status: 'pending', order: 20 },
  { id: 'prata-21', stageId: 's3', title: 'Usando map, filter e spread operator', status: 'pending', order: 21 },
  { id: 'prata-22', stageId: 's3', title: 'Find e reduce', status: 'pending', order: 22 },
  { id: 'prata-23', stageId: 's3', title: 'Desestruturação de objetos: extraindo dados facilmente', status: 'pending', order: 23 },
  { id: 'prata-24', stageId: 's3', title: 'Exercícios - Arrays e objetos', status: 'pending', order: 24 },
  { id: 'prata-25', stageId: 's3', title: 'Introdução ao DOM e seletores', status: 'pending', order: 25 },
  { id: 'prata-26', stageId: 's3', title: 'Eventos no JS - clique, input e submit no formulário de busca', status: 'pending', order: 26 },
  { id: 'prata-27', stageId: 's3', title: 'Alterando classes e atributos com JS', status: 'pending', order: 27 },
  { id: 'prata-28', stageId: 's3', title: 'Renderizando arrays dinamicamente no DOM', status: 'pending', order: 28 },
  { id: 'prata-29', stageId: 's3', title: 'APIs e JSON: Como o JavaScript conversa com o mundo', status: 'pending', order: 29 },
  { id: 'prata-30', stageId: 's3', title: 'Promises e async/await: Como lidar com código assíncrono no JavaScript', status: 'pending', order: 30 },
  { id: 'prata-31', stageId: 's3', title: 'Try/Catch - Lidando com erros e carregamento de dados', status: 'pending', order: 31 },
  { id: 'prata-32', stageId: 's3', title: 'Buscando múltiplos filmes com Promise.all e Promise.allSettled (API Studio Ghibli)', status: 'pending', order: 32 },
  { id: 'prata-33', stageId: 's3', title: 'O que é o localStorage', status: 'pending', order: 33 },
  { id: 'prata-34', stageId: 's3', title: 'Criando modo escuro com toggle + localStorage', status: 'pending', order: 34 },
  { id: 'prata-35', stageId: 's3', title: 'Exercícios Práticos de Consumo de APIs', status: 'pending', order: 35 },
  { id: 'prata-36', stageId: 's3', title: 'Apresentando o projeto e a estrutura inicial', status: 'pending', order: 36 },
  { id: 'prata-37', stageId: 's3', title: 'Buscando os dados do usuário pela API do GitHub', status: 'pending', order: 37 },
  { id: 'prata-38', stageId: 's3', title: 'Renderizando total de seguidores e seguindo e refatoração', status: 'pending', order: 38 },
  { id: 'prata-39', stageId: 's3', title: 'Buscando os repositórios do usuário pela API do GitHub', status: 'pending', order: 39 },
  { id: 'prata-40', stageId: 's3', title: 'Subindo o projeto para o GitHub Pages', status: 'pending', order: 40 },
  { id: 'prata-41', stageId: 's3', title: 'Projeto: Projeto pra consolidar o JS', status: 'pending', order: 41 },
  { id: 'prata-42', stageId: 's3', title: 'Prática Frontend Mentor — JavaScript', status: 'pending', order: 42 },
  { id: 'prata-43', stageId: 's3', title: 'Aprendi sobre o conceito: Lógica de controle (if/loop/função)', description: 'Conceito-chave', status: 'pending', order: 43 },
  { id: 'prata-44', stageId: 's3', title: 'Aprendi sobre o conceito: Manipulação de dados (array/obj/map/filter/reduce)', description: 'Conceito-chave', status: 'pending', order: 44 },
  { id: 'prata-45', stageId: 's3', title: 'Aprendi sobre o conceito: DOM orientado a eventos', description: 'Conceito-chave', status: 'pending', order: 45 },
  { id: 'prata-46', stageId: 's3', title: 'Aprendi sobre o conceito: Assíncrono com async/await e tratamento de erro', description: 'Conceito-chave', status: 'pending', order: 46 },

  // ---------- Etapa 4 – Ouro ----------
  { id: 'ouro-1', stageId: 's4', title: 'Entendendo o TypeScript', status: 'pending', order: 1 },
  { id: 'ouro-2', stageId: 's4', title: 'Instalação e primeiros passos de uso', status: 'pending', order: 2 },
  { id: 'ouro-3', stageId: 's4', title: 'Entenda os tipos no TypeScript - Parte 1', status: 'pending', order: 3 },
  { id: 'ouro-4', stageId: 's4', title: 'Entenda os tipos no TypeScript - Parte 2', status: 'pending', order: 4 },
  { id: 'ouro-5', stageId: 's4', title: 'Tipagem explicita e inferência de tipo', status: 'pending', order: 5 },
  { id: 'ouro-6', stageId: 's4', title: 'Sendo mais produtivo com a verificação de tipo estático', status: 'pending', order: 6 },
  { id: 'ouro-7', stageId: 's4', title: 'Tipos Tuples: uma coleção mais específica que o Array', status: 'pending', order: 7 },
  { id: 'ouro-8', stageId: 's4', title: 'Tipos Enums: facilitando o entendimento do código', status: 'pending', order: 8 },
  { id: 'ouro-9', stageId: 's4', title: 'Exercício - TypeScript: Usando enums', status: 'pending', order: 9 },
  { id: 'ouro-10', stageId: 's4', title: 'Desabilitar tipagem com tipo Any', status: 'pending', order: 10 },
  { id: 'ouro-11', stageId: 's4', title: 'Tipagem em funções', status: 'pending', order: 11 },
  { id: 'ouro-12', stageId: 's4', title: 'Exercícios - TypeScript: Tipagem em funções', status: 'pending', order: 12 },
  { id: 'ouro-13', stageId: 's4', title: 'Unions: unindo um ou mais tipos', status: 'pending', order: 13 },
  { id: 'ouro-14', stageId: 's4', title: 'Exercício - TypeScript: Usando union types', status: 'pending', order: 14 },
  { id: 'ouro-15', stageId: 's4', title: 'Type aliases: dando apelidos aos nossos tipos', status: 'pending', order: 15 },
  { id: 'ouro-16', stageId: 's4', title: 'Tipagem de objetos', status: 'pending', order: 16 },
  { id: 'ouro-17', stageId: 's4', title: 'Propriedades e parâmetros opcionais', status: 'pending', order: 17 },
  { id: 'ouro-18', stageId: 's4', title: 'Especificando tipos com Type Assertions', status: 'pending', order: 18 },
  { id: 'ouro-19', stageId: 's4', title: 'Interfaces: mais uma forma de nomear tipos de objetos', status: 'pending', order: 19 },
  { id: 'ouro-20', stageId: 's4', title: 'Exercício - TypeScript: Usando interfaces', status: 'pending', order: 20 },
  { id: 'ouro-21', stageId: 's4', title: 'Generics: deixando o código reutilizável', status: 'pending', order: 21 },
  { id: 'ouro-22', stageId: 's4', title: 'Exercício - TypeScript: Trabalhando com Generics', status: 'pending', order: 22 },
  { id: 'ouro-23', stageId: 's4', title: 'Import e export de módulo no TS', status: 'pending', order: 23 },
  { id: 'ouro-24', stageId: 's4', title: 'TS Config: Configurando o TS dos nossos projetos', status: 'pending', order: 24 },
  { id: 'ouro-25', stageId: 's4', title: 'Introdução ao React', status: 'pending', order: 25 },
  { id: 'ouro-26', stageId: 's4', title: 'Introdução Vite vs Create React App', status: 'pending', order: 26 },
  { id: 'ouro-27', stageId: 's4', title: 'O que é o VITE?', status: 'pending', order: 27 },
  { id: 'ouro-28', stageId: 's4', title: 'Inicializando um projeto com Vite', status: 'pending', order: 28 },
  { id: 'ouro-29', stageId: 's4', title: 'Estrutura de um projeto React', status: 'pending', order: 29 },
  { id: 'ouro-30', stageId: 's4', title: 'Fluxo de Renderização no React com Vite: App.tsx, main.tsx e index.html', status: 'pending', order: 30 },
  { id: 'ouro-31', stageId: 's4', title: 'Introdução ao JSX', status: 'pending', order: 31 },
  { id: 'ouro-32', stageId: 's4', title: 'JSX na prática', status: 'pending', order: 32 },
  { id: 'ouro-33', stageId: 's4', title: 'Componentes de função vs Componentes de classe', status: 'pending', order: 33 },
  { id: 'ouro-34', stageId: 's4', title: 'Props', status: 'pending', order: 34 },
  { id: 'ouro-35', stageId: 's4', title: 'Exercício - Props: Recebendo e renderizando props', status: 'pending', order: 35 },
  { id: 'ouro-36', stageId: 's4', title: 'Props Default', status: 'pending', order: 36 },
  { id: 'ouro-37', stageId: 's4', title: 'Props Children', status: 'pending', order: 37 },
  { id: 'ouro-38', stageId: 's4', title: 'Renderização condicional', status: 'pending', order: 38 },
  { id: 'ouro-39', stageId: 's4', title: 'Hooks: useState', status: 'pending', order: 39 },
  { id: 'ouro-40', stageId: 's4', title: 'Exercício - React: Contador com limite personalizado', status: 'pending', order: 40 },
  { id: 'ouro-41', stageId: 's4', title: 'Trabalhando com listas', status: 'pending', order: 41 },
  { id: 'ouro-42', stageId: 's4', title: 'Trabalhando com eventos', status: 'pending', order: 42 },
  { id: 'ouro-43', stageId: 's4', title: 'Exercício - React: Trabalhando com eventos', status: 'pending', order: 43 },
  { id: 'ouro-44', stageId: 's4', title: 'Estilização no React', status: 'pending', order: 44 },
  { id: 'ouro-45', stageId: 's4', title: 'Introdução ao projeto Com React + TS + Tailwind', status: 'pending', order: 45 },
  { id: 'ouro-46', stageId: 's4', title: 'Conhecendo o TailwindCSS', status: 'pending', order: 46 },
  { id: 'ouro-47', stageId: 's4', title: 'Largura, altura, flexbox e responsividade no Tailwind', status: 'pending', order: 47 },
  { id: 'ouro-48', stageId: 's4', title: 'Estilizando com TailwindCSS', status: 'pending', order: 48 },
  { id: 'ouro-49', stageId: 's4', title: 'Conhecendo a Context API', status: 'pending', order: 49 },
  { id: 'ouro-50', stageId: 's4', title: 'Context API - partes 1 e 2 - Finalizando o Header e a TodoList', status: 'pending', order: 50 },
  { id: 'ouro-51', stageId: 's4', title: 'Context API - parte 3 - Alterando a imagem de fundo', status: 'pending', order: 51 },
  { id: 'ouro-52', stageId: 's4', title: 'Context API - parte 4 - correção dos erros e hovers', status: 'pending', order: 52 },
  { id: 'ouro-53', stageId: 's4', title: 'Desenvolvendo a parte lógica da aplicação - Adicionando uma tarefa', status: 'pending', order: 53 },
  { id: 'ouro-54', stageId: 's4', title: 'Desenvolvendo a parte lógica - Renderizando as tarefas na tela', status: 'pending', order: 54 },
  { id: 'ouro-55', stageId: 's4', title: 'Desenvolvendo a parte lógica da aplicação - Filtrando tarefas', status: 'pending', order: 55 },
  { id: 'ouro-56', stageId: 's4', title: 'Hooks customizados', status: 'pending', order: 56 },
  { id: 'ouro-57', stageId: 's4', title: 'Exercícios - React Fundamentos', status: 'pending', order: 57 },
  { id: 'ouro-58', stageId: 's4', title: 'Automações com N8N', status: 'pending', order: 58 },
  { id: 'ouro-59', stageId: 's4', title: 'Projeto: Projeto fundo mágico', status: 'pending', order: 59 },
  { id: 'ouro-60', stageId: 's4', title: 'Projeto: BotFlix', status: 'pending', order: 60 },
  { id: 'ouro-61', stageId: 's4', title: 'Aprendi sobre o conceito: Tipagem prática com TypeScript', description: 'Conceito-chave', status: 'pending', order: 61 },
  { id: 'ouro-62', stageId: 's4', title: 'Aprendi sobre o conceito: Estado e renderização no React', description: 'Conceito-chave', status: 'pending', order: 62 },
  { id: 'ouro-63', stageId: 's4', title: 'Aprendi sobre o conceito: Composição de componentes e props', description: 'Conceito-chave', status: 'pending', order: 63 },
  { id: 'ouro-64', stageId: 's4', title: 'Aprendi sobre o conceito: Gestão de estado inicial (Context + hooks)', description: 'Conceito-chave', status: 'pending', order: 64 },

  // ---------- Etapa 5 – Platina ----------
  { id: 'platina-1', stageId: 's5', title: 'useEffect', status: 'pending', order: 1 },
  { id: 'platina-2', stageId: 's5', title: 'Exercício - React: Buscando dados de uma API', status: 'pending', order: 2 },
  { id: 'platina-3', stageId: 's5', title: 'Gerenciamento de formulários com Zod', status: 'pending', order: 3 },
  { id: 'platina-4', stageId: 's5', title: 'React Hook Form', status: 'pending', order: 4 },
  { id: 'platina-5', stageId: 's5', title: 'Exercício - React: Adicionando mais campos de validação com Zod', status: 'pending', order: 5 },
  { id: 'platina-6', stageId: 's5', title: 'React Router Dom', status: 'pending', order: 6 },
  { id: 'platina-7', stageId: 's5', title: 'useParams', status: 'pending', order: 7 },
  { id: 'platina-8', stageId: 's5', title: 'Client Side Rendering (CSR)', status: 'pending', order: 8 },
  { id: 'platina-9', stageId: 's5', title: 'Ciclo de Vida no React', status: 'pending', order: 9 },
  { id: 'platina-10', stageId: 's5', title: 'Code Splitting,  Lazy Loading e Suspense', status: 'pending', order: 10 },
  { id: 'platina-11', stageId: 's5', title: 'TanStack Query: O Jeito Inteligente de Buscar Dados no React', status: 'pending', order: 11 },
  { id: 'platina-12', stageId: 's5', title: 'Exercícios - React avançado', status: 'pending', order: 12 },
  { id: 'platina-13', stageId: 's5', title: 'Desafio - Consumindo a API do Studio Ghibli com React e TypeScript', status: 'pending', order: 13 },
  { id: 'platina-14', stageId: 's5', title: 'Introdução', status: 'pending', order: 14 },
  { id: 'platina-15', stageId: 's5', title: 'A importância da criação das redes sociais', status: 'pending', order: 15 },
  { id: 'platina-16', stageId: 's5', title: 'O que é backend?', status: 'pending', order: 16 },
  { id: 'platina-17', stageId: 's5', title: 'Por que é bom separar o frontend do backend?', status: 'pending', order: 17 },
  { id: 'platina-18', stageId: 's5', title: 'Node.js - Trabalhando com JavaScript no backend', status: 'pending', order: 18 },
  { id: 'platina-19', stageId: 's5', title: 'O que são bancos de dados?', status: 'pending', order: 19 },
  { id: 'platina-20', stageId: 's5', title: 'Conhecendo o SQL', status: 'pending', order: 20 },
  { id: 'platina-21', stageId: 's5', title: 'Diferenças entre SQL e NoSQL', status: 'pending', order: 21 },
  { id: 'platina-22', stageId: 's5', title: 'Instalação do PostegreSQL', status: 'pending', order: 22 },
  { id: 'platina-23', stageId: 's5', title: 'Instalação do DBeaver', status: 'pending', order: 23 },
  { id: 'platina-24', stageId: 's5', title: 'Estrutura de um banco de dados', status: 'pending', order: 24 },
  { id: 'platina-25', stageId: 's5', title: 'Tipos de dados', status: 'pending', order: 25 },
  { id: 'platina-26', stageId: 's5', title: 'Chaves primárias', status: 'pending', order: 26 },
  { id: 'platina-27', stageId: 's5', title: 'Chaves estrangeiras', status: 'pending', order: 27 },
  { id: 'platina-28', stageId: 's5', title: 'Comando INSERT - Inserindo dados - Parte 1', status: 'pending', order: 28 },
  { id: 'platina-29', stageId: 's5', title: 'Comando INSERT - Inserindo dados - Parte 2', status: 'pending', order: 29 },
  { id: 'platina-30', stageId: 's5', title: 'Comando UPDATE - Atualizando dados do banco', status: 'pending', order: 30 },
  { id: 'platina-31', stageId: 's5', title: 'Comando DELETE - Atualizando dados do banco', status: 'pending', order: 31 },
  { id: 'platina-32', stageId: 's5', title: 'Comando SELECT - Selecionando dados do banco - PARTE 1', status: 'pending', order: 32 },
  { id: 'platina-33', stageId: 's5', title: 'Comando SELECT e JOIN - Selecionando dados em mais de uma tabela', status: 'pending', order: 33 },
  { id: 'platina-34', stageId: 's5', title: 'Complemento - JOIN', status: 'pending', order: 34 },
  { id: 'platina-35', stageId: 's5', title: 'Operadores lógicos - Parte 1', status: 'pending', order: 35 },
  { id: 'platina-36', stageId: 's5', title: 'Operadores lógicos - Parte 2', status: 'pending', order: 36 },
  { id: 'platina-37', stageId: 's5', title: 'Operadores matemáticos', status: 'pending', order: 37 },
  { id: 'platina-38', stageId: 's5', title: 'Exercício 1', status: 'pending', order: 38 },
  { id: 'platina-39', stageId: 's5', title: 'O que é HTTP?', status: 'pending', order: 39 },
  { id: 'platina-40', stageId: 's5', title: 'Como funciona a comunicação via HTTP', status: 'pending', order: 40 },
  { id: 'platina-41', stageId: 's5', title: 'Visão geral de uma requisição', status: 'pending', order: 41 },
  { id: 'platina-42', stageId: 's5', title: 'Visualizando as requisições no DevTools', status: 'pending', order: 42 },
  { id: 'platina-43', stageId: 's5', title: 'Headers', status: 'pending', order: 43 },
  { id: 'platina-44', stageId: 's5', title: 'Métodos HTTP', status: 'pending', order: 44 },
  { id: 'platina-45', stageId: 's5', title: 'Status Codes HTTP', status: 'pending', order: 45 },
  { id: 'platina-46', stageId: 's5', title: 'Corpo da requisição', status: 'pending', order: 46 },
  { id: 'platina-47', stageId: 's5', title: 'URL: Passando parâmetros', status: 'pending', order: 47 },
  { id: 'platina-48', stageId: 's5', title: 'O objetivo principal do currículo do dev iniciante', status: 'pending', order: 48 },
  { id: 'platina-49', stageId: 's5', title: 'A escolha do template', status: 'pending', order: 49 },
  { id: 'platina-50', stageId: 's5', title: 'Informações que precisam estar no seu currículo', status: 'pending', order: 50 },
  { id: 'platina-51', stageId: 's5', title: 'Sugestão de estrutura de um currículo que se destaca', status: 'pending', order: 51 },
  { id: 'platina-52', stageId: 's5', title: 'Como demonstrar experiência, mesmo sem ter trabalhado na área', status: 'pending', order: 52 },
  { id: 'platina-53', stageId: 's5', title: 'Como se cadastrar no LinkedIn', status: 'pending', order: 53 },
  { id: 'platina-54', stageId: 's5', title: 'Objetivo do LinkedIn', status: 'pending', order: 54 },
  { id: 'platina-55', stageId: 's5', title: 'Estrutura básica de um perfil no LinkedIn de sucesso', status: 'pending', order: 55 },
  { id: 'platina-56', stageId: 's5', title: 'SEJA ATIVO(A)!', status: 'pending', order: 56 },
  { id: 'platina-57', stageId: 's5', title: 'Já tenho um perfil antigo, o que fazer?', status: 'pending', order: 57 },
  { id: 'platina-58', stageId: 's5', title: 'Melhorando suas chances com o LinkedIn premium', status: 'pending', order: 58 },
  { id: 'platina-59', stageId: 's5', title: 'Comecei a receber propostas de emprego, e agora?', status: 'pending', order: 59 },
  { id: 'platina-60', stageId: 's5', title: 'Empregabilidade e dicas', status: 'pending', order: 60 },
  { id: 'platina-61', stageId: 's5', title: 'Empresas, vagas e aplicações', status: 'pending', order: 61 },
  { id: 'platina-62', stageId: 's5', title: 'Dicas de preparação, insegurança e timidez', status: 'pending', order: 62 },
  { id: 'platina-63', stageId: 's5', title: 'Projeto: DevLingo', status: 'pending', order: 63 },
  { id: 'platina-64', stageId: 's5', title: 'Aprendi sobre o conceito: Roteamento em SPA', description: 'Conceito-chave', status: 'pending', order: 64 },
  { id: 'platina-65', stageId: 's5', title: 'Aprendi sobre o conceito: Validação de formulários', description: 'Conceito-chave', status: 'pending', order: 65 },
  { id: 'platina-66', stageId: 's5', title: 'Aprendi sobre o conceito: Busca de dados e cache (TanStack Query)', description: 'Conceito-chave', status: 'pending', order: 66 },
  { id: 'platina-67', stageId: 's5', title: 'Aprendi sobre o conceito: Posicionamento profissional (CV + LinkedIn orientados a vaga)', description: 'Conceito-chave', status: 'pending', order: 67 },
  { id: 'platina-68', stageId: 's5', title: 'Assistir aula: Próximos passos', status: 'pending', order: 68 },
  { id: 'platina-69', stageId: 's5', title: 'Atualizar redes com o rank Platina', status: 'pending', order: 69 },

  // ---------- Etapa 6 – Esmeralda ----------
  { id: 'esmeralda-1', stageId: 's6', title: 'Conhecimentos necessários para o módulo de Node.js', status: 'pending', order: 1 },
  { id: 'esmeralda-2', stageId: 's6', title: 'Instalando o Node.js', status: 'pending', order: 2 },
  { id: 'esmeralda-3', stageId: 's6', title: 'Executando scripts na linha de comando', status: 'pending', order: 3 },
  { id: 'esmeralda-4', stageId: 's6', title: 'Diferenças entre o node e o navegador', status: 'pending', order: 4 },
  { id: 'esmeralda-5', stageId: 's6', title: 'Criando um módulo', status: 'pending', order: 5 },
  { id: 'esmeralda-6', stageId: 's6', title: 'Entendendo os módulos do Node.js', status: 'pending', order: 6 },
  { id: 'esmeralda-7', stageId: 's6', title: 'Manipulando arquivos', status: 'pending', order: 7 },
  { id: 'esmeralda-8', stageId: 's6', title: 'Como criar um servidor HTTP com Node.js', status: 'pending', order: 8 },
  { id: 'esmeralda-9', stageId: 's6', title: 'Criando rotas para o nosso servidor', status: 'pending', order: 9 },
  { id: 'esmeralda-10', stageId: 's6', title: 'Configurando o NPM', status: 'pending', order: 10 },
  { id: 'esmeralda-11', stageId: 's6', title: 'Sendo mais produtivo(a) com Nodemon', status: 'pending', order: 11 },
  { id: 'esmeralda-12', stageId: 's6', title: 'Comando node —watch', status: 'pending', order: 12 },
  { id: 'esmeralda-13', stageId: 's6', title: 'Introdução ao Express', status: 'pending', order: 13 },
  { id: 'esmeralda-14', stageId: 's6', title: 'Testando API no VS Code com Thunder Client', status: 'pending', order: 14 },
  { id: 'esmeralda-15', stageId: 's6', title: 'Rotas no express', status: 'pending', order: 15 },
  { id: 'esmeralda-16', stageId: 's6', title: 'Rotas com parâmetros', status: 'pending', order: 16 },
  { id: 'esmeralda-17', stageId: 's6', title: 'Métodos de resposta', status: 'pending', order: 17 },
  { id: 'esmeralda-18', stageId: 's6', title: 'Mesma rota com métodos diferentes', status: 'pending', order: 18 },
  { id: 'esmeralda-19', stageId: 's6', title: 'Chain of Responsability', status: 'pending', order: 19 },
  { id: 'esmeralda-20', stageId: 's6', title: 'O que é Middleware?', status: 'pending', order: 20 },
  { id: 'esmeralda-21', stageId: 's6', title: 'Middleware na prática - Application-level middleware', status: 'pending', order: 21 },
  { id: 'esmeralda-22', stageId: 's6', title: 'Middleware na prática - Error Handling middleware', status: 'pending', order: 22 },
  { id: 'esmeralda-23', stageId: 's6', title: 'Middleware na prática - Middlewares de terceiros', status: 'pending', order: 23 },
  { id: 'esmeralda-24', stageId: 's6', title: 'Middleware na prática - Middlewares do Express', status: 'pending', order: 24 },
  { id: 'esmeralda-25', stageId: 's6', title: 'Grupo de rotas', status: 'pending', order: 25 },
  { id: 'esmeralda-26', stageId: 's6', title: 'Route Handlers', status: 'pending', order: 26 },
  { id: 'esmeralda-27', stageId: 's6', title: 'Servindo arquivos estáticos', status: 'pending', order: 27 },
  { id: 'esmeralda-28', stageId: 's6', title: 'Tratando erros', status: 'pending', order: 28 },
  { id: 'esmeralda-29', stageId: 's6', title: 'O que vamos criar?', status: 'pending', order: 29 },
  { id: 'esmeralda-30', stageId: 's6', title: 'Requisitos funcionais do projeto', status: 'pending', order: 30 },
  { id: 'esmeralda-31', stageId: 's6', title: 'Configurações iniciais', status: 'pending', order: 31 },
  { id: 'esmeralda-32', stageId: 's6', title: 'Configurações iniciais - Parte 2', status: 'pending', order: 32 },
  { id: 'esmeralda-33', stageId: 's6', title: 'Deixando o código padronizado com ESLint', status: 'pending', order: 33 },
  { id: 'esmeralda-34', stageId: 's6', title: 'ESLint - NOVA ATUALIZAÇÃO', status: 'pending', order: 34 },
  { id: 'esmeralda-35', stageId: 's6', title: 'Instalando o Express', status: 'pending', order: 35 },
  { id: 'esmeralda-36', stageId: 's6', title: 'Introdução ao Prisma e iniciando a conexão com o banco', status: 'pending', order: 36 },
  { id: 'esmeralda-37', stageId: 's6', title: 'Atualização de versão do Prisma', status: 'pending', order: 37 },
  { id: 'esmeralda-38', stageId: 's6', title: 'Criando os models de um banco já existente', status: 'pending', order: 38 },
  { id: 'esmeralda-39', stageId: 's6', title: 'Criando os models de um banco já existente - Parte 2', status: 'pending', order: 39 },
  { id: 'esmeralda-40', stageId: 's6', title: 'Models do Prisma - ATUALIZAÇÃO', status: 'pending', order: 40 },
  { id: 'esmeralda-41', stageId: 's6', title: 'Ordenando e adicionando relacionamentos na listagem de filmes', status: 'pending', order: 41 },
  { id: 'esmeralda-42', stageId: 's6', title: 'Cadastro de um filme', status: 'pending', order: 42 },
  { id: 'esmeralda-43', stageId: 's6', title: 'Cadastro de um filme - Parte 2', status: 'pending', order: 43 },
  { id: 'esmeralda-44', stageId: 's6', title: 'Validando filmes com títulos duplicados', status: 'pending', order: 44 },
  { id: 'esmeralda-45', stageId: 's6', title: 'Atualizando um filme', status: 'pending', order: 45 },
  { id: 'esmeralda-46', stageId: 's6', title: 'Atualizando um filme - Parte 2', status: 'pending', order: 46 },
  { id: 'esmeralda-47', stageId: 's6', title: 'Removendo um filme', status: 'pending', order: 47 },
  { id: 'esmeralda-48', stageId: 's6', title: 'Filtrar filmes por gênero', status: 'pending', order: 48 },
  { id: 'esmeralda-49', stageId: 's6', title: 'Swagger para documentação e endpoints', status: 'pending', order: 49 },
  { id: 'esmeralda-50', stageId: 's6', title: 'Configurando o swagger na aplicação', status: 'pending', order: 50 },
  { id: 'esmeralda-51', stageId: 's6', title: 'Criando a documentação da rota de atualização de filme', status: 'pending', order: 51 },
  { id: 'esmeralda-52', stageId: 's6', title: 'Criando a documentação do delete', status: 'pending', order: 52 },
  { id: 'esmeralda-53', stageId: 's6', title: 'Criando a a documentação da rota de filtro de filmes por gênero', status: 'pending', order: 53 },
  { id: 'esmeralda-54', stageId: 's6', title: 'Gerando o build do projeto', status: 'pending', order: 54 },
  { id: 'esmeralda-55', stageId: 's6', title: 'Conclusão do módulo', status: 'pending', order: 55 },
  { id: 'esmeralda-56', stageId: 's6', title: 'Introdução ao Docker', status: 'pending', order: 56 },
  { id: 'esmeralda-57', stageId: 's6', title: 'Entendendo imagens e containers', status: 'pending', order: 57 },
  { id: 'esmeralda-58', stageId: 's6', title: 'Docker Hub', status: 'pending', order: 58 },
  { id: 'esmeralda-59', stageId: 's6', title: 'Instalando o Docker Desktop', status: 'pending', order: 59 },
  { id: 'esmeralda-60', stageId: 's6', title: 'Dockerfile', status: 'pending', order: 60 },
  { id: 'esmeralda-61', stageId: 's6', title: 'Docker Compose', status: 'pending', order: 61 },
  { id: 'esmeralda-62', stageId: 's6', title: 'Volumes e persistências de dados', status: 'pending', order: 62 },
  { id: 'esmeralda-63', stageId: 's6', title: 'Primeiros passos com o Docker', status: 'pending', order: 63 },
  { id: 'esmeralda-64', stageId: 's6', title: 'Dicas de Docker para testes técnicos', status: 'pending', order: 64 },
  { id: 'esmeralda-65', stageId: 's6', title: 'Apresentando o módulo', status: 'pending', order: 65 },
  { id: 'esmeralda-66', stageId: 's6', title: 'Introdução', status: 'pending', order: 66 },
  { id: 'esmeralda-70', stageId: 's6', title: 'Migrations', status: 'pending', order: 70 },
  { id: 'esmeralda-72', stageId: 's6', title: 'Conhecendo o Prisma Client', status: 'pending', order: 72 },
  { id: 'esmeralda-75', stageId: 's6', title: 'Métodos do Prisma (Create, Update e Delete)', status: 'pending', order: 75 },
  { id: 'esmeralda-76', stageId: 's6', title: 'Métodos de busca de registros (findUnique e findMany)', status: 'pending', order: 76 },
  { id: 'esmeralda-77', stageId: 's6', title: 'Relações com chave estrangeira dentro do Prisma', status: 'pending', order: 77 },
  { id: 'esmeralda-78', stageId: 's6', title: 'Transaction', status: 'pending', order: 78 },
  { id: 'esmeralda-80', stageId: 's6', title: 'Exercício 1', status: 'pending', order: 80 },
  { id: 'esmeralda-81', stageId: 's6', title: 'Desafio - Node.JS e Express: Criando API de Todos com Node.js e TypeScript', status: 'pending', order: 81 },
  { id: 'esmeralda-82', stageId: 's6', title: 'Projeto: Projeto com Node e PostgreSQL', status: 'pending', order: 82 },
  { id: 'esmeralda-83', stageId: 's6', title: 'Aprendi sobre o conceito: Arquitetura REST', description: 'Conceito-chave', status: 'pending', order: 83 },
  { id: 'esmeralda-84', stageId: 's6', title: 'Aprendi sobre o conceito: Modelagem relacional e SQL prático', description: 'Conceito-chave', status: 'pending', order: 84 },
  { id: 'esmeralda-85', stageId: 's6', title: 'Aprendi sobre o conceito: Camada de API com Express (rotas/middlewares/erros)', description: 'Conceito-chave', status: 'pending', order: 85 },
  { id: 'esmeralda-86', stageId: 's6', title: 'Aprendi sobre o conceito: ORM com Prisma (CRUD + relações)', description: 'Conceito-chave', status: 'pending', order: 86 },
  { id: 'esmeralda-87', stageId: 's6', title: 'Aprendi sobre o conceito: Deploy de APIs', description: 'Conceito-chave', status: 'pending', order: 87 },
  { id: 'esmeralda-88', stageId: 's6', title: 'Atualizar currículo com conceitos e projetos do rank Esmeralda (última tarefa)', status: 'pending', order: 88 },

  // ---------- Etapa 7 – Diamante ----------
  { id: 'diamante-1', stageId: 's7', title: 'O que é IA e por que ela vai mudar o rumo do mercado de programação', status: 'pending', order: 1 },
  { id: 'diamante-2', stageId: 's7', title: 'Ferramentas de IA para Acelerar o Desenvolvimento de Código', status: 'pending', order: 2 },
  { id: 'diamante-3', stageId: 's7', title: 'Utilizando IA na Busca e Candidatura de Vagas', status: 'pending', order: 3 },
  { id: 'diamante-7', stageId: 's7', title: 'JavaScript que você precisa saber para trabalhar com REACT', status: 'pending', order: 7 },
  { id: 'diamante-8', stageId: 's7', title: 'Como criar um projeto do zero sem travar', status: 'pending', order: 8 },
  { id: 'diamante-9', stageId: 's7', title: 'Criando um projeto do zero do frontend mentor utilizando figma', status: 'pending', order: 9 },
  { id: 'diamante-10', stageId: 's7', title: 'Codando com o monitor Pablo', status: 'pending', order: 10 },
  { id: 'diamante-11', stageId: 's7', title: 'Projeto Receita', status: 'pending', order: 11 },
  { id: 'diamante-12', stageId: 's7', title: 'Projeto fundo mágico', status: 'pending', order: 12 },
  { id: 'diamante-13', stageId: 's7', title: 'Quando eu uso Divs!? Aprenda a criar um HTML que não vai dar dor de cabeça', status: 'pending', order: 13 },
  { id: 'diamante-14', stageId: 's7', title: 'Produtividade máxima nos estudos', status: 'pending', order: 14 },
  { id: 'diamante-15', stageId: 's7', title: 'Projeto: FinTrack AI', status: 'pending', order: 15 },
  { id: 'diamante-16', stageId: 's7', title: 'Projeto: Syntax Wear Frontend', status: 'pending', order: 16 },
  { id: 'diamante-17', stageId: 's7', title: 'Projeto: Syntax Wear Backend', status: 'pending', order: 17 },
  { id: 'diamante-18', stageId: 's7', title: 'Aprendi sobre o conceito: Autenticação e autorização', description: 'Conceito-chave', status: 'pending', order: 18 },
  { id: 'diamante-19', stageId: 's7', title: 'Aprendi sobre o conceito: Integração full stack orientada a produto', description: 'Conceito-chave', status: 'pending', order: 19 },
  { id: 'diamante-20', stageId: 's7', title: 'Aprendi sobre o conceito: IA aplicada em fluxo real (não só demo)', description: 'Conceito-chave', status: 'pending', order: 20 },
  { id: 'diamante-21', stageId: 's7', title: 'Aprendi sobre o conceito: Qualidade de entrega (teste, observabilidade, manutenção)', description: 'Conceito-chave', status: 'pending', order: 21 },
  { id: 'diamante-22', stageId: 's7', title: 'Atualizar currículo com conceitos e projetos do rank Diamante (última tarefa)', status: 'pending', order: 22 },

  // ---------- Etapa 8 – Mythril ----------
  { id: 'mythril-1', stageId: 's8', title: 'Projeto: Syntax Wear Integração', status: 'pending', order: 1 },
  { id: 'mythril-2', stageId: 's8', title: 'Projeto: PetShop', status: 'pending', order: 2 },
  { id: 'mythril-3', stageId: 's8', title: 'Freela com IA', status: 'pending', order: 3 },
  { id: 'mythril-4', stageId: 's8', title: 'Formação JS Avançado com Next.js', status: 'pending', order: 4 },
  { id: 'mythril-5', stageId: 's8', title: 'Portfólio publicado', status: 'pending', order: 5 },
  { id: 'mythril-6', stageId: 's8', title: 'Projeto pessoal autoral', status: 'pending', order: 6 },
  { id: 'mythril-7', stageId: 's8', title: 'Aprendi sobre o conceito: Projeto autoral de ponta a ponta', description: 'Conceito-chave', status: 'pending', order: 7 },
  { id: 'mythril-8', stageId: 's8', title: 'Aprendi sobre o conceito: Portfólio com narrativa de impacto', description: 'Conceito-chave', status: 'pending', order: 8 },
  { id: 'mythril-9', stageId: 's8', title: 'Aprendi sobre o conceito: Escopo e entrega para cliente/freela', description: 'Conceito-chave', status: 'pending', order: 9 },
  { id: 'mythril-10', stageId: 's8', title: 'Atualizar currículo com conceitos e projetos do rank Mythril (última tarefa)', status: 'pending', order: 10 },

  // ---------- Etapa 9 – Mestre ----------
  { id: 'mestre-1', stageId: 's9', title: 'Simulação de entrevista técnica', status: 'pending', order: 1 },
  { id: 'mestre-2', stageId: 's9', title: 'No mínimo 50 candidaturas enviadas', status: 'pending', order: 2 },
  { id: 'mestre-3', stageId: 's9', title: '1 entrevista real realizada', status: 'pending', order: 3 },
  { id: 'mestre-4', stageId: 's9', title: 'Monitorias com Tech Recruiter', status: 'pending', order: 4 },
  { id: 'mestre-5', stageId: 's9', title: 'Networking ativo', status: 'pending', order: 5 },
  { id: 'mestre-6', stageId: 's9', title: 'Aprendi sobre o conceito: Estratégia de candidaturas', description: 'Conceito-chave', status: 'pending', order: 6 },
  { id: 'mestre-7', stageId: 's9', title: 'Aprendi sobre o conceito: Entrevista técnica e comportamental', description: 'Conceito-chave', status: 'pending', order: 7 },
  { id: 'mestre-8', stageId: 's9', title: 'Aprendi sobre o conceito: Comunicação profissional e networking', description: 'Conceito-chave', status: 'pending', order: 8 },
  { id: 'mestre-9', stageId: 's9', title: 'Atualizar currículo com conceitos e projetos do rank Mestre (última tarefa)', status: 'pending', order: 9 },

  // ---------- Etapa 10 – Lendário ----------
  { id: 'lendario-1', stageId: 's10', title: '3 freelas entregues para clientes reais', description: 'Conceito-chave', status: 'pending', order: 1 },
  { id: 'lendario-2', stageId: 's10', title: 'Ganhar R$5.000+ com programação', description: 'Conceito-chave', status: 'pending', order: 2 },
  { id: 'lendario-3', stageId: 's10', title: 'Primeira vaga na área', description: 'Conceito-chave', status: 'pending', order: 3 },
  { id: 'lendario-4', stageId: 's10', title: 'Mentorar outro aluno', description: 'Conceito-chave', status: 'pending', order: 4 },
  { id: 'lendario-5', stageId: 's10', title: 'Atualizar currículo e redes com o rank Lendário', description: 'Conceito-chave', status: 'pending', order: 5 },
];
